version: '3'

services:
  app:
    image: ghcr.io/pengpercy/duck2api:latest
    container_name: duck2api
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - chromedp
  chromedp:
    image: chromedp/headless-shell:stable
    container_name: chromedp
    command:
      - "--disable-blink-features=AutomationControlled"